### ISSUE TITLE
Feature/button to upload files from local storage and download them

### ISSUE THREAD

**Issue by carme24036** [David24461/SkillSwap#8]
- This feature would be used for uploading resumes and cover letters and downloading them from a user's profile
- Access to downloading and uploading the files would be on the profiles via a link or a button

**Comment by csmith1188** [comment]
Make sure you can find and use the file after it is uploaded.

Maybe just a download resume link on the user profile.

**Comment by isabellafeliciano1** [comment]
This issue was completed. A new issue was made to fix the server side so that the files could be uploaded correctly.
